Attempt testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,11 +1,10 @@
 name: CI
 
-# Trigger this workflow on push or pull request
 on: [push, pull_request]
 
 jobs:
   build-linux:
-    name: Build (Linux)
+    name: Build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -22,8 +21,17 @@ jobs:
         run: |
           mkdir build
           cd build
-          cmake ..
+          cmake .. -DENABLE_TESTS=ON
       - name: Build
         run: |
           cd build
           cmake --build . -j8
+      - name: Run CTest
+        run: |
+          cd build
+          ctest --output-on-failure --output-junit report.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # Run even if tests fail
+        with:
+          report_paths: '**/build/report.xml'
